name: gedit
version: git
summary: Edit text files
description: |
  gedit is the official text editor of the GNOME desktop environment.
  While aiming at simplicity and ease of use, gedit is a powerful general
  purpose text editor.

  Whether you are writing the next bestseller, programming an innovative
  application, or simply taking some quick notes, gedit will be a reliable
  tool to accomplish your task.

  Its flexible plugin system allows you to tailor the application to your
  needs and adapt it to your workflow.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core18

plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

slots:
  # for GtkApplication registration
  gedit:
    interface: dbus
    bus: session
    name: org.gnome.gedit

apps:
  gedit:
    command: desktop-launch gedit
    plugs:
      - avahi-observe
      - cups-control
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - mount-observe
      - removable-media
      - unity7
      - wayland
    desktop: usr/share/applications/org.gnome.gedit.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib/gedit

parts:
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform

  gtksourceview:
    after: [desktop-gnome-platform]
    source: https://gitlab.gnome.org/GNOME/gtksourceview.git
    source-type: git
    source-tag: 4.0.3
    plugin: autotools
    configflags: [--prefix=/usr]
    organize:
      snap/gtksourceview/current/usr: usr
    build-packages:
      - autoconf-archive
      - gettext
      - gobject-introspection
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libpeas-dev
      - libxml2-dev
      - libxml2-utils
      - valac

  gedit:
    after: [gtksourceview]
    source: https://gitlab.gnome.org/GNOME/gedit.git
    source-type: git
 #   source-tag: 3.30.2
    plugin: meson
    meson-parameters:
      - --prefix=/snap/gedit/current/usr
      - -Dintrospection=false
    build-environment:
      - PKG_CONFIG_PATH: $SNAPCRAFT_STAGE/usr/lib/pkgconfig
      - VAPIDIR: $SNAPCRAFT_STAGE/usr/share/vala/vapi
    override-build: |
       sed -i.bak -e 's|Icon=org.gnome.gedit$|Icon=${SNAP}/meta/gui/org.gnome.gedit.svg|g' data/org.gnome.gedit.desktop.in.in
       snapcraftctl build
       mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
       cp data/org.gnome.gedit.svg $SNAPCRAFT_PART_INSTALL/meta/gui/
       cp ../install/snap/gedit/current/usr/share/applications/org.gnome.gedit.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    organize:
      snap/gedit/current/usr: usr
    build-packages:
      - desktop-file-utils
      - gettext
      - gsettings-desktop-schemas-dev
      - gtk-doc-tools
      - itstool
      - libsoup2.4-dev
      - libgspell-1-dev
      - libxml2-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libpeas-dev
      - libx11-dev
      - python3
      - python-gi-dev
      - gobject-introspection
      - libgirepository1.0-dev
      - valac
