name: gedit
version: git
adopt-info: gedit
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core18

passthrough:
  layout:
    /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpeas-1.0:
      symlink: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpeas-1.0
    /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gedit:
      symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gedit
    /usr/share/gedit:
      symlink: $SNAP/usr/share/gedit
    /usr/share/xml/iso-codes:
      symlink: $SNAP/gnome-platform/usr/share/xml/iso-codes

plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

slots:
  # for GtkApplication registration
  gedit:
    interface: dbus
    bus: session
    name: org.gnome.gedit

apps:
  gedit:
    command: desktop-launch gedit
    plugs:
      - avahi-observe
      - cups-control
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - mount-observe
      - removable-media
      - unity7
      - wayland
    common-id: org.gnome.gedit.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET/gedit
      GI_TYPELIB_PATH: $SNAP/usr/lib/girepository-1.0:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0:$SNAP/gnome-platform/usr/lib/girepository-1.0:$SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/gnome-platform/usr/lib/python3/dist-packages

parts:
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform

  gtksourceview:
    source: https://gitlab.gnome.org/GNOME/gtksourceview.git
    source-type: git
    plugin: autotools
    configflags: [--prefix=/snap/gedit/current/usr]
    organize:
      snap/gedit/current/usr: usr
    build-packages:
      - autoconf-archive
      - gettext
      - gobject-introspection
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libpeas-dev
      - libxml2-dev
      - libxml2-utils
      - valac
    # meson gir overrides don't work well
    override-build: |
       snapcraftctl build
       cp $SNAPCRAFT_PART_INSTALL/snap/gedit/current/usr/share/gir-1.0/GtkSource* /usr/share/gir-1.0
       cp $SNAPCRAFT_PART_INSTALL/snap/gedit/current/usr/share/vala/vapi/gtksource* /usr/share/vala/vapi

  gedit:
    after: [desktop-gnome-platform, gtksourceview]
    source: .
    source-type: git
    parse-info: [usr/share/metainfo/org.gnome.gedit.appdata.xml]
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    build-environment:
      - C_INCLUDE_PATH: $SNAPCRAFT_STAGE/usr/include/gtksourceview-4
    override-build: |
       sed -i.bak -e 's|Icon=org.gnome.gedit$|Icon=${SNAP}/meta/gui/org.gnome.gedit.svg|g' data/org.gnome.gedit.desktop.in.in
       sed -i.bak -e "s|symlink_media: true|symlink_media: false|g" help/meson.build
       snapcraftctl build
       mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
       cp data/org.gnome.gedit.svg $SNAPCRAFT_PART_INSTALL/meta/gui/
       cp ../install/usr/share/applications/org.gnome.gedit.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    build-packages:
      - desktop-file-utils
      - gettext
      - gsettings-desktop-schemas-dev
      - gtk-doc-tools
      - itstool
      - libsoup2.4-dev
      - libgspell-1-dev
      - libxml2-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libpeas-dev
      - libx11-dev
      - python3
      - python-gi-dev
      - gobject-introspection
      - libgirepository1.0-dev
      - valac

  gedit-plugins:
    after: [gedit]
    source: https://gitlab.gnome.org/GNOME/gedit-plugins.git
    source-type: git
    plugin: autotools
    # gedit's meson build uses the triplet libdir but gedit-plugin's
    # autotools doesn't. They need to match.
    configflags:
      - --prefix=/snap/gedit/current/usr
      - --libdir=/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
    organize:
      snap/gedit/current/usr: usr
    build-environment:
      - C_INCLUDE_PATH: $SNAPCRAFT_STAGE/usr/include:$SNAPCRAFT_STAGE/usr/include/gedit-3.14:$SNAPCRAFT_STAGE/usr/include/gtksourceview-4
      - LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gedit
      - PKG_CONFIG_PATH: $PKG_CONFIG_PATH:$SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig
    build-packages:
      - appstream
      - build-essential
      - gettext
      - gnome-common
      - itstool
      - libgit2-glib-1.0-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libgucharmap-2-90-dev
      - libvte-2.91-dev
      - python3
      - python3-dbus
      - python-dbus-dev
      - python-gi-dev
      - yelp-tools
# Overriding VAPIDIR in build-environment doesn't seem to work
    override-build: |
      sed -i.bak -e 's|--pkg\ config|--vapidir=$SNAPCRAFT_STAGE/usr/share/vala/vapi\ --pkg\ config|g' plugins/findinfiles/Makefile.am
      sed -i.bak -e 's|--pkg\ config|--vapidir=$SNAPCRAFT_STAGE/usr/share/vala/vapi\ --pkg\ config|g' plugins/findinfiles/Makefile.am
      snapcraftctl build
# Zeitgeist plugin isn't as useful in a Snap.
    stage:
      - -usr/lib/gedit/plugins/libzeitgeist.so
      - -usr/lib/gedit/plugins/zeitgeist.plugin
      - -usr/share/help/*/gedit/zeitgeist-dataprovider.page
      - -usr/share/metainfo/gedit-zeitgeist.metainfo.xml
